"""Prepare satellite photo tiles of a flying field for the WL Avionics widget.

Imagery: USGS NAIP (The National Map), US public domain, ~0.6 m/px, USA only.

The widget map zooms in fixed steps (100 ft, 200 ft, 500 ft ... 5 mi = radius of the range
ring). For every step this script renders 256x256 JPG tiles at exactly the screen
resolution of that step (ring meters / ring pixels), so the radio never scales images:
one image pixel = one screen pixel. Fine steps cover a smaller radius around the field
(they are only used while the whole flight is close to home).

Each widget layout has its own ring size in pixels, so tiles are made per layout:
    --radio mk2      WL Avionics (attitude indicator + map), TX16S MK2 480x272: ring 43 px, 256 px tiles
    --radio mk2full  WL Maps (full-height map),              TX16S MK2 480x272: ring 111 px, 256 px tiles
    --radio mk3      WL Avionics,                            TX16S MK3 800x480: ring 85 px, 512 px tiles
    --radio mk3full  WL Maps,                                TX16S MK3 800x480: ring 207 px, 512 px tiles
    --radio all      both layouts of this project's screen size (DEFAULT_SCREEN below)
Tiles are big enough that at most 2x2 are visible (EdgeTX keeps 8 decoded images cached).

    python tools/maptiles/make_field.py --name ama --lat 40.1666 --lon -85.3195 --radius-mi 5 --radio all

Output (copy the WLMAP folder to the root of the radio SD card; all widgets share it):
    tools/maptiles/out/WLMAP/fields.lua            field list read by the widgets
    tools/maptiles/out/WLMAP/<name>/<ring px>/<level>/<col>_<row>.jpg
"""
import argparse
import io
import json
import shutil
import math
import os
import sys
import threading
import time
import urllib.request
from concurrent.futures import ThreadPoolExecutor

from PIL import Image, ImageEnhance

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "out", "WLMAP")
SERVICE = "https://imagery.nationalmap.gov/arcgis/rest/services/USGSNAIPImagery/ImageServer/exportImage"
UA = "WLAvionics tile prep (personal RC use)"
R_EARTH = 6378137.0
FT, MI = 0.3048, 1609.344

# Must match STEPS.imperial in WIDGETS/WLAvionics/map.lua (same order = same level index)
STEPS = [100 * FT, 200 * FT, 500 * FT, 1000 * FT, 2000 * FT, 0.5 * MI, 1 * MI, 2 * MI, 5 * MI, 10 * MI, 20 * MI]
LABELS = ["100 ft", "200 ft", "500 ft", "1000 ft", "2000 ft", "0.5 mi", "1 mi", "2 mi", "5 mi", "10 mi", "20 mi"]
NLEVELS = 9   # up to the 5 mi step

# Per widget layout: range ring radius in pixels (map.lua: r = map height / 2 - 6) and the
# coverage radius (miles) of the three finest levels; coarser levels cover the whole field.
RADIOS = {
    "mk2": {"ring": 43, "tile": 256, "fine_mi": [0.5, 1, 2], "max_n": 24},
    "mk2full": {"ring": 111, "tile": 256, "fine_mi": [0.25, 0.5, 1], "max_n": 24},   # bigger map = more px per mile
    "mk3": {"ring": 85, "tile": 512, "fine_mi": [0.5, 1, 2], "max_n": 16},
    "mk3full": {"ring": 207, "tile": 512, "fine_mi": [0.25, 0.5, 1], "max_n": 16},
}
SCREENS = {"480x272": ["mk2", "mk2full"], "800x480": ["mk3", "mk3full"]}
DEFAULT_SCREEN = "480x272"   # this project's radio screen
# max_n: max tiles per side and level (coarser levels still reach the full radius)


def mercator(lat, lon):
    return math.radians(lon) * R_EARTH, math.log(math.tan(math.pi / 4 + math.radians(lat) / 2)) * R_EARTH


def fetch(bbox, size, darken, quality, retries=4):
    url = (f"{SERVICE}?bbox={bbox[0]:.3f},{bbox[1]:.3f},{bbox[2]:.3f},{bbox[3]:.3f}"
           f"&bboxSR=3857&imageSR=3857&size={size},{size}&format=jpg"
           f"&interpolation=RSP_BilinearInterpolation&f=image")
    for attempt in range(retries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            data = urllib.request.urlopen(req, timeout=60).read()
            im = Image.open(io.BytesIO(data)).convert("RGB")
            if im.size != (size, size):
                raise ValueError(f"unexpected size {im.size}")
            if darken != 1.0:
                im = ImageEnhance.Brightness(im).enhance(darken)
            buf = io.BytesIO()
            im.save(buf, "JPEG", quality=quality, optimize=True)  # baseline JPEG (stb_image friendly)
            return buf.getvalue()
        except Exception as e:  # network hiccup / server busy: back off and retry
            if attempt == retries - 1:
                raise RuntimeError(f"tile failed after {retries} tries: {e}")
            time.sleep(2 * (attempt + 1))


def write_fields_lua(registry):
    lines = ["-- WL Avionics: flying fields with photo tiles. Generated by tools/maptiles/make_field.py",
             "-- (do not edit by hand; re-run the script). rings[<ring px>][<zoom step index>] = tiles per side.",
             "return {"]
    for f in registry.values():
        lines.append(f'  {{ name = "{f["name"]}", lat = {f["lat"]:.8f}, lon = {f["lon"]:.8f}, '
                     f'radius = {f["radius_m"]:.0f}, units = "imperial", rings = {{')
        for ring, levels in sorted(f["rings"].items(), key=lambda kv: int(kv[0])):
            tile = levels.get("tile", 256)
            lv = ", ".join(f"[{k}] = {{ n = {n} }}" for k, n in sorted((int(k), n) for k, n in levels.items()
                                                                        if k != "tile"))
            lines.append(f"    [{ring}] = {{ tile = {tile}, {lv} }},")
        lines.append("  } },")
    lines.append("}")
    with open(os.path.join(OUT, "fields.lua"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--name", required=True, help="short field name (letters/digits, <= 8 chars)")
    ap.add_argument("--lat", type=float, required=True)
    ap.add_argument("--lon", type=float, required=True)
    ap.add_argument("--radius-mi", type=float, default=5.0)
    ap.add_argument("--radio", choices=sorted(RADIOS) + ["all"], default="all")
    ap.add_argument("--darken", type=float, default=0.8, help="brightness factor so overlays stand out")
    ap.add_argument("--quality", type=int, default=80)
    ap.add_argument("--workers", type=int, default=3, help="parallel downloads (be polite)")
    ap.add_argument("--min-level", type=int, default=1,
                    help="first zoom level with photo (4 = 1000 ft): skip the fine levels for big areas")
    ap.add_argument("--dry-run", action="store_true", help="only print the tile plan")
    ap.add_argument("--out", default=None, help="output WLMAP folder (default: tools/maptiles/out/WLMAP)")
    a = ap.parse_args()
    global OUT
    if a.out:
        OUT = os.path.abspath(a.out)

    name = a.name.lower()
    if not name.isalnum() or len(name) > 8:
        sys.exit("--name: use up to 8 letters/digits")
    radius_m = a.radius_mi * MI
    cx, cy = mercator(a.lat, a.lon)
    k = 1 / math.cos(math.radians(a.lat))   # mercator meters per ground meter at the field
    radios = SCREENS[DEFAULT_SCREEN] if a.radio == "all" else [a.radio]

    plan, rings = [], {}
    for rk in radios:
        ring, TILE = RADIOS[rk]["ring"], RADIOS[rk]["tile"]
        fine = RADIOS[rk]["fine_mi"]
        levels = {}
        print(f"{rk}: ring {ring} px")
        for li, step in enumerate(STEPS[:NLEVELS], start=1):
            if li < a.min_level:
                continue
            cov = min(radius_m, fine[li - 1] * MI) if li <= len(fine) else radius_m
            mpp = step / ring                     # ground meters per screen pixel at this zoom
            n = min(RADIOS[rk]["max_n"], max(1, math.ceil(2 * cov / (mpp * TILE))))
            levels[li] = n
            half = n * TILE / 2
            for j in range(n):
                for i in range(n):
                    # tile pixel box relative to the field center (x east, y south)
                    x0, y0 = i * TILE - half, j * TILE - half
                    bbox = (cx + x0 * mpp * k, cy - (y0 + TILE) * mpp * k,
                            cx + (x0 + TILE) * mpp * k, cy - y0 * mpp * k)
                    plan.append((ring, li, i, j, bbox, TILE))
            print(f"  level {li:2d} {LABELS[li - 1]:>7}: {mpp:7.2f} m/px  {n}x{n} tiles  "
                  f"covers {n * TILE * mpp / MI / 2:.2f} mi radius")
        rings[str(ring)] = {str(k2): v for k2, v in levels.items()}
        rings[str(ring)]["tile"] = TILE
    print(f"{len(plan)} tiles for '{name}'")
    if a.dry_run:
        return

    base = os.path.join(OUT, name)
    # Tile names depend on the grid size: a level folder made with another grid (or tile size) is wiped
    for ring, levels in rings.items():
        for li, n in levels.items():
            if li == "tile":
                continue
            d = os.path.join(base, ring, li)
            mark = os.path.join(d, "grid.txt")
            want = f"{n} {levels['tile']}"
            if os.path.isdir(d):
                have = open(mark).read().strip() if os.path.exists(mark) else None
                if have is not None and have != want:
                    print(f"  ring {ring} level {li}: grid changed ({have} -> {want}), re-downloading")
                    shutil.rmtree(d)
            os.makedirs(d, exist_ok=True)
            with open(mark, "w") as fh:
                fh.write(want)

    def tile_path(p):
        return os.path.join(base, str(p[0]), str(p[1]), f"{p[2]}_{p[3]}.jpg")
    todo = [p for p in plan if not os.path.exists(tile_path(p))]
    print(f"{len(plan) - len(todo)} already downloaded, {len(todo)} to go")
    lock, done = threading.Lock(), [0]

    def work(p):
        data = fetch(p[4], p[5], a.darken, a.quality)
        dst = tile_path(p)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        with open(dst + ".tmp", "wb") as fh:
            fh.write(data)
        os.replace(dst + ".tmp", dst)
        with lock:
            done[0] += 1
            if done[0] % 50 == 0 or done[0] == len(todo):
                print(f"  {done[0]}/{len(todo)}", flush=True)

    with ThreadPoolExecutor(max_workers=max(1, min(a.workers, 4))) as ex:
        list(ex.map(work, todo))

    reg_path = os.path.join(OUT, "fields.json")
    registry = {}
    if os.path.exists(reg_path):
        with open(reg_path, encoding="utf-8") as fh:
            registry = json.load(fh)
    entry = registry.get(name) or {}
    old_rings = entry.get("rings", {})
    old_rings.update(rings)
    registry[name] = {"name": name, "lat": a.lat, "lon": a.lon, "radius_m": radius_m, "rings": old_rings}
    with open(reg_path, "w", encoding="utf-8") as fh:
        json.dump(registry, fh, indent=2)
    write_fields_lua(registry)

    size = sum(os.path.getsize(os.path.join(dp, f)) for dp, _, fs in os.walk(base) for f in fs)
    print(f"done: {size / 1e6:.1f} MB in {base}")
    print(f"copy {OUT} to the SD card root as /WLMAP")


if __name__ == "__main__":
    main()
